import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { SiteShell } from '@/components/site-shell'
import { ContentCard } from '@/components/content-card'
import { articles } from '@/lib/content'
export default function Page() { return <SiteShell><main>
  <section className="hero wrap"><div className="eyebrow"><span className="signal-dot" /> Redefining digital innovation</div><h1>Building<br /><em>tomorrow&apos;s</em><br /><strong>technology.</strong></h1><div className="hero-bottom"><p>Lumyn Technologies is a Nairobi-based studio crafting enterprise-grade software — from M-Pesa-integrated platforms to AI-assisted products — for businesses ready to move faster than their market.</p><div className="hero-actions"><Link href="/contact" className="button button-dark">Start your project <ArrowUpRight size={16} /></Link><Link href="/articles" className="button button-outline">Explore our insights</Link></div></div><div className="stats"><div><b>12<span>+</span></b><small>Projects delivered</small></div><div><b>4<span>+</span></b><small>Team members</small></div><div><b>3<span>+</span></b><small>Events hosted</small></div><div><b>2<span>+</span></b><small>Years of innovation</small></div></div></section>
  <div className="ticker"><div>STRATEGY <i>✦</i> DESIGN <i>✦</i> ENGINEERING <i>✦</i> MOMENTUM <i>✦</i> STRATEGY <i>✦</i> DESIGN <i>✦</i> ENGINEERING <i>✦</i> MOMENTUM <i>✦</i></div></div>
  <section className="section wrap" id="insights"><div className="section-heading"><div><span className="section-label">Latest insights</span><h2>Ideas for businesses ready to move</h2></div><Link href="/articles" className="text-link">View all insights <ArrowUpRight size={16} /></Link></div><div className="card-grid">{articles.slice(0, 3).map((item) => <ContentCard key={item.slug} item={item} />)}</div></section>
</main></SiteShell> }