import Link from 'next/link'
import { ArrowDown, ArrowUpRight, Check } from 'lucide-react'
import { SiteShell } from '@/components/site-shell'
import { ContentCard } from '@/components/content-card'
import { articles, news } from '@/lib/content'

export default function Page() { return <SiteShell><main>
  <section className="hero wrap"><div className="eyebrow"><span className="signal-dot" /> Redefining digital innovation</div><h1>Building<br /><em>tomorrow&apos;s</em><br /><strong>technology.</strong></h1><div className="hero-bottom"><p>Lumyn Technologies is a Nairobi-based studio crafting enterprise-grade software — from M-Pesa-integrated platforms to AI-assisted products — for businesses ready to move faster than their market.</p><div className="hero-actions"><Link href="/#contact" className="button button-dark">Start your project <ArrowUpRight size={16} /></Link><Link href="/articles" className="button button-outline">Explore our insights</Link></div></div><div className="stats"><div><b>12<span>+</span></b><small>Projects delivered</small></div><div><b>4<span>+</span></b><small>Team members</small></div><div><b>3<span>+</span></b><small>Events hosted</small></div><div><b>2<span>+</span></b><small>Years of innovation</small></div></div></section>
  <div className="ticker"><div>STRATEGY <i>✦</i> DESIGN <i>✦</i> ENGINEERING <i>✦</i> MOMENTUM <i>✦</i> STRATEGY <i>✦</i> DESIGN <i>✦</i> ENGINEERING <i>✦</i> MOMENTUM <i>✦</i></div></div>
  <section className="capabilities" id="capabilities"><div className="cap-row"><span>01</span><h2>Discover</h2><p>We learn how your business works, where it is going, and what your customers need next.</p><Check /></div><div className="cap-row"><span>02</span><h2>Design</h2><p>We turn complex requirements into clear journeys, useful systems, and a sharp digital point of view.</p><Check /></div><div className="cap-row"><span>03</span><h2>Build</h2><p>We engineer reliable products with modern technology, resilient infrastructure, and measurable performance.</p><Check /></div><div className="cap-row"><span>04</span><h2>Grow</h2><p>We stay close after launch to improve adoption, learn from real usage, and help your product compound.</p><Check /></div></section>
  <section className="section wrap" id="about"><div className="section-heading"><div><span className="section-label">Who we are</span><h2>Pioneering the future of digital innovation</h2></div><ArrowDown /></div><div className="principles"><div><div className="principle-mark" /><h3>Enterprise solutions</h3><p>Scalable architecture built for mission-critical requirements, from M-Pesa payment rails to multi-tenant platforms.</p></div><div><div className="principle-mark" /><h3>Cutting-edge technology</h3><p>Leveraging AI, cloud-native architectures, and modern development practices across every build.</p></div><div><div className="principle-mark" /><h3>Global impact</h3><p>Trusted by businesses across Kenya and beyond to drive real digital transformation.</p></div></div></section>
  <section className="section wrap" id="insights"><div className="section-heading"><div><span className="section-label">Latest insights</span><h2>Ideas for businesses ready to move</h2></div><Link href="/articles" className="text-link">View all insights <ArrowUpRight size={16} /></Link></div><div className="card-grid">{articles.slice(0, 3).map((item) => <ContentCard key={item.slug} item={item} />)}</div></section>
  <section className="cta"><div className="wrap"><span className="section-label">Let&apos;s build together</span><h2>Ready to transform <em>your vision?</em></h2><p>Partner with Lumyn Technologies and let&apos;s build the future together.</p><Link href="mailto:info@lumyn.co.ke" className="button button-orange">Start a conversation <ArrowUpRight size={16} /></Link></div></section>
</main></SiteShell> }
